<a href="https://colab.research.google.com/github/TurboNeso/Testrepo/blob/main/Webscraping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="300" alt="cognitiveclass.ai logo">
</center>

# Simple APIs 
## Random User and Fruitvice API Examples


Estimated time needed: **25** minutes

## Objectives

After completing this lab you will be able to:

*   Load and use RandomUser API, using `RandomUser()` Python library
*   Load and use Fruitvice API, using `requests` Python library

The purpose of this notebook is to provide more examples on how to use simple APIs. As you have already learned from previous videos and notebooks, API stands for Application Programming Interface and is a software intermediary that allows two applications to talk to each other. 

The advantages of using APIs:
 *   **Automation**. Less human effort is required and workflows can be easily updated to become faster and more      
     productive.
 *   **Efficiency**. It allows to use the capabilities of one of the already developed APIs than to try to 
     independently implement some functionality from scratch.
 
The disadvantage of using APIs:
 *   **Secirity**. If the API is poorly integrated, it means it will be vulnerable to attacks, resulting in data    
     breeches or losses having financial or reputation implications.

One of the applications we will use in this notebook is Random User Generator. RandomUser is an open-source, free API providing developers with randomly generated users to be used as placeholders for testing purposes. This makes the tool similar to Lorem Ipsum, but is a placeholder for people instead of text. The API can return multiple results, as well as specify generated user details such as gender, email, image, username, address, title, first and last name, and more. More information on [RandomUser](https://randomuser.me/documentation?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork1005-2022-01-01#intro) can be found here.

Another example of simple API we will use in this notebook is Fruitvice application. The Fruitvice API webservice which provides data for all kinds of fruit! You can use Fruityvice to find out interesting information about fruit and educate yourself. The webservice is completely free to use and contribute to.

## Example 1: RandomUser API
Bellow are Get Methods parameters that we can generate. For more information on the parameters, please visit this [documentation](https://randomuser.me/documentation?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork1005-2022-01-01) page.

## **Get Methods**

- get_cell()
- get_city()
- get_dob()
- get_email()
- get_first_name()
- get_full_name()
- get_gender()
- get_id()
- get_id_number()
- get_id_type()
- get_info()
- get_last_name()
- get_login_md5()
- get_login_salt()
- get_login_sha1()
- get_login_sha256()
- get_nat()
- get_password()
- get_phone()
- get_picture()
- get_postcode()
- get_registered()
- get_state()
- get_street()
- get_username()
- get_zipcode()

To start using the API you can install the `randomuser` library running the `pip install` command.

In [2]:
!pip install Randomuser

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting Randomuser
  Downloading randomuser-1.6.tar.gz (5.0 kB)
Building wheels for collected packages: Randomuser
  Building wheel for Randomuser (setup.py) ... done
  Created wheel for Randomuser: filename=randomuser-1.6-py3-none-any.whl size=5083 sha256=7f3921eec2a292d555d40b91a710515d0b656838eabd83dcaebbba7164a5df8b
  Stored in directory: /root/.cache/pip/wheels/17/a5/f9/554200008d8fc0d9ad077722bf27cde01be06cebedadc24600
Successfully built Randomuser
Installing collected packages: Randomuser
Successfully installed Randomuser-1.6

In [3]:
from randomuser import RandomUser
import pandas as pd

First, we will create a random user object, r.

In [4]:
r = RandomUser()

Then, using `generate_users()` function, we get a list of random 10 users.

In [5]:
some_list = r.generate_users(10)

In [6]:
some_list

[<randomuser.RandomUser at 0x7fb97da02130>,
 <randomuser.RandomUser at 0x7fb97c99ae80>,
 <randomuser.RandomUser at 0x7fb97c99a520>,
 <randomuser.RandomUser at 0x7fb97c99af40>,
 <randomuser.RandomUser at 0x7fb97c98b490>,
 <randomuser.RandomUser at 0x7fb990c6a490>,
 <randomuser.RandomUser at 0x7fb990c6a4f0>,
 <randomuser.RandomUser at 0x7fb990c6a3d0>,
 <randomuser.RandomUser at 0x7fb979f29820>,
 <randomuser.RandomUser at 0x7fb979f29880>]

The **"Get Methods"** functions mentioned at the beginning of this notebook, can generate the required parameters to construct a dataset. For example, to get full name, we call `get_full_name()` function.

In [7]:
name = r.get_full_name()

In [8]:
name

'Ronnie Ray'

Let's say we only need 10 users with full names and their email addresses. We can write a "for-loop" to print these 10 users.

In [9]:
for user in some_list:
  print(user.get_full_name(), " ", user.get_email())

Rosario Flores   rosario.flores@example.com
Helmi Hokkanen   helmi.hokkanen@example.com
Lionel Robin   lionel.robin@example.com
Viivi Jutila   viivi.jutila@example.com
Aleksi Lehtola   aleksi.lehtola@example.com
مانی جعفری   mny.jaafry@example.com
Violeta Daniëls   violeta.daniels@example.com
Kelly Watts   kelly.watts@example.com
Signe Møller   signe.moller@example.com
Ryan Chu   ryan.chu@example.com

In [10]:
# Using get_picture to get pic of users
for user in some_list:
  print(user.get_picture())

https://randomuser.me/api/portraits/women/43.jpg
https://randomuser.me/api/portraits/women/60.jpg
https://randomuser.me/api/portraits/men/8.jpg
https://randomuser.me/api/portraits/women/82.jpg
https://randomuser.me/api/portraits/men/61.jpg
https://randomuser.me/api/portraits/men/82.jpg
https://randomuser.me/api/portraits/women/87.jpg
https://randomuser.me/api/portraits/women/36.jpg
https://randomuser.me/api/portraits/women/72.jpg
https://randomuser.me/api/portraits/men/10.jpg

To generate a table with information about the users, we can write a function containing all desirable parameters. For example, name, gender, city, etc. The parameters will depend on the requirements of the test to be performed. We call the Get Methods, listed at the beginning of this notebook. Then, we return pandas dataframe with the users.

In [11]:
def get_user():
  user_list =[]
  for user in RandomUser.generate_users(10):
    user_list.append({'Name':user.get_full_name(), 'Gender': user.get_gender(), 'City':user.get_city(),'State': user.get_state(), 'Email': user.get_email(), 'DOB':user.get_dob(), 'Picture': user.get_picture()})
  return pd.DataFrame(user_list)

In [12]:
get_user()

,Name,Gender,City,State,Email,DOB,Picture
0,Benjamin Larsen,male,Argerskov,Hovedstaden,benjamin.larsen@example.com,1987-01-06T05:13:42.221Z,https://randomuser.me/api/portraits/men/49.jpg
1,اميرعلي جعفری,male,رشت,تهران,myraaly.jaafry@example.com,1995-11-26T06:33:43.990Z,https://randomuser.me/api/portraits/men/32.jpg
2,Vera Sviggum,female,Haga,Akershus,vera.sviggum@example.com,1972-05-01T08:21:55.490Z,https://randomuser.me/api/portraits/women/50.jpg
3,Ismael Martinez,male,Orihuela,Castilla y León,ismael.martinez@example.com,1971-04-26T02:29:41.329Z,https://randomuser.me/api/portraits/men/41.jpg
4,Tamara Castro,female,Bragança,Rio Grande do Sul,tamara.castro@example.com,1972-02-12T14:24:55.994Z,https://randomuser.me/api/portraits/women/24.jpg
5,Isaltino Gonçalves,male,Campinas,Rio de Janeiro,isaltino.goncalves@example.com,1944-09-17T12:40:30.372Z,https://randomuser.me/api/portraits/men/77.jpg
6,Yolanda Santiago,female,Arrecife,Islas Baleares,yolanda.santiago@example.com,1976-11-18T08:08:41.396Z,https://randomuser.me/api/portraits/women/2.jpg
7,Angèle Dumas,female,Lyon,Haute-Marne,angele.dumas@example.com,1968-10-22T06:52:28.910Z,https://randomuser.me/api/portraits/women/57.jpg
8,Yahya Langfeldt,male,Årnset,Vest-Agder,yahya.langfeldt@example.com,1981-11-07T13:32:21.539Z,https://randomuser.me/api/portraits/men/85.jpg
9,Kenneth Wright,male,Aberdeen,Rutland,kenneth.wright@example.com,1989-07-04T20:36:00.587Z,https://randomuser.me/api/portraits/men/45.jpg

In [13]:
df1 = pd.DataFrame(get_user())

In [14]:
df1

,Name,Gender,City,State,Email,DOB,Picture
0,Illias Verwey,male,Utrechtse Heuvelrug,Zuid-Holland,illias.verwey@example.com,1985-02-28T00:16:10.431Z,https://randomuser.me/api/portraits/men/1.jpg
1,Malthe Larsen,male,Noerre Alslev,Hovedstaden,malthe.larsen@example.com,1954-12-21T19:13:31.396Z,https://randomuser.me/api/portraits/men/35.jpg
2,آدرین گلشن,male,مشهد,یزد,adryn.glshn@example.com,1979-09-25T15:26:26.727Z,https://randomuser.me/api/portraits/men/3.jpg
3,Romina Philippe,female,Ostermundigen,Zürich,romina.philippe@example.com,1973-05-16T07:24:59.012Z,https://randomuser.me/api/portraits/women/28.jpg
4,Meghan Gonzalez,female,Bundaberg,Australian Capital Territory,meghan.gonzalez@example.com,1969-09-01T10:27:30.611Z,https://randomuser.me/api/portraits/women/88.jpg
5,Pihla Kujala,female,Hausjärvi,Northern Savonia,pihla.kujala@example.com,1949-07-31T22:54:45.164Z,https://randomuser.me/api/portraits/women/6.jpg
6,Dimitrios Baar,male,Lemelerveld,Flevoland,dimitrios.baar@example.com,1962-08-21T16:47:51.805Z,https://randomuser.me/api/portraits/men/34.jpg
7,Jerry Palmer,male,Ely,County Tyrone,jerry.palmer@example.com,1982-11-05T16:16:21.114Z,https://randomuser.me/api/portraits/men/98.jpg
8,Dylan Johnson,male,Belmont,Nova Scotia,dylan.johnson@example.com,1957-07-24T09:45:22.526Z,https://randomuser.me/api/portraits/men/83.jpg
9,Ali Beşok,male,Çanakkale,Mersin,ali.besok@example.com,1954-08-22T11:41:13.311Z,https://randomuser.me/api/portraits/men/83.jpg

## Example 2: Fruitvice API

Another, more common way to use APIs, is through `requests` library. The next lab, Requests and HTTP, will contain more information about requests.

We will start by importing all required libraries.

In [15]:
import requests as r
import json

We will obtain the [fruitvice](https://www.fruityvice.com/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork1005-2022-01-01) API data using `requests.get("url")` function. The data is in a json format.

In [16]:
data = r.get("https://www.fruityvice.com/api/fruit/all")

We will retrieve results using `json.loads()` function.

In [17]:
result = json.loads(data.text)

In [18]:
df = pd.DataFrame(result)

In [19]:
df

,genus,name,id,family,order,nutritions
0,Malus,Apple,6,Rosaceae,Rosales,"{'carbohydrates': 11.4, 'protein': 0.3, 'fat':..."
1,Prunus,Apricot,35,Rosaceae,Rosales,"{'carbohydrates': 3.9, 'protein': 0.5, 'fat': ..."
2,Persea,Avocado,84,Lauraceae,Laurales,"{'carbohydrates': 8.53, 'protein': 2, 'fat': 1..."
3,Musa,Banana,1,Musaceae,Zingiberales,"{'carbohydrates': 22, 'protein': 1, 'fat': 0.2..."
4,Rubus,Blackberry,64,Rosaceae,Rosales,"{'carbohydrates': 9, 'protein': 1.3, 'fat': 0...."
5,Fragaria,Blueberry,33,Rosaceae,Rosales,"{'carbohydrates': 5.5, 'protein': 0, 'fat': 0...."
6,Prunus,Cherry,9,Rosaceae,Rosales,"{'carbohydrates': 12, 'protein': 1, 'fat': 0.3..."
7,Theobroma,Chocolate,88,Malvaceae,Malvales,"{'carbohydrates': 58, 'protein': 8.51, 'fat': ..."
8,Vaccinium,Cranberry,87,Ericaceae,Ericales,"{'carbohydrates': 12.2, 'protein': 0.4, 'fat':..."
9,Selenicereus,Dragonfruit,80,Cactaceae,Caryophyllales,"{'carbohydrates': 9, 'protein': 9, 'fat': 1.5,..."
10,Durio,Durian,60,Malvaceae,Malvales,"{'carbohydrates': 27.1, 'protein': 1.5, 'fat':..."
11,Sellowiana,Feijoa,76,Myrtaceae,Myrtoideae,"{'carbohydrates': 8, 'protein': 0.6, 'fat': 0...."
12,Ficus,Fig,68,Moraceae,Rosales,"{'carbohydrates': 19, 'protein': 0.8, 'fat': 0..."
13,Ribes,Gooseberry,69,Grossulariaceae,Saxifragales,"{'carbohydrates': 10, 'protein': 0.9, 'fat': 0..."
14,Vitis,Grape,81,Vitaceae,Vitales,"{'carbohydrates': 18.1, 'protein': 0.72, 'fat'..."
15,Vitis,Grapes,47,Vitaceae,Vitales,"{'carbohydrates': 18.1, 'protein': 0.72, 'fat'..."
16,Malus,GreenApple,72,Rosaceae,Rosales,"{'carbohydrates': 3.1, 'protein': 0.4, 'fat': ..."
17,Psidium,Guava,37,Myrtaceae,Myrtales,"{'carbohydrates': 14, 'protein': 2.6, 'fat': 1..."
18,Apteryx,Kiwi,66,Actinidiaceae,Struthioniformes,"{'carbohydrates': 15, 'protein': 1.1, 'fat': 0..."
19,Actinidia,Kiwifruit,85,Actinidiaceae,Ericales,"{'carbohydrates': 14.6, 'protein': 1.14, 'fat'..."
20,Citrus,Lemon,26,Rutaceae,Sapindales,"{'carbohydrates': 9, 'protein': 1.1, 'fat': 0...."
21,Citrus,Lime,44,Rutaceae,Sapindales,"{'carbohydrates': 8.4, 'protein': 0.3, 'fat': ..."
22,Vaccinium,Lingonberry,65,Ericaceae,Ericales,"{'carbohydrates': 11.3, 'protein': 0.75, 'fat'..."
23,Litchi,Lychee,67,Sapindaceae,Sapindales,"{'carbohydrates': 17, 'protein': 0.8, 'fat': 0..."
24,Mangifera,Mango,27,Anacardiaceae,Sapindales,"{'carbohydrates': 15, 'protein': 0.82, 'fat': ..."
25,Cucumis,Melon,41,Cucurbitaceae,Cucurbitaceae,"{'carbohydrates': 8, 'protein': 0, 'fat': 0, '..."
26,Morus,Morus,82,Moraceae,Rosales,"{'carbohydrates': 9.8, 'protein': 1.44, 'fat':..."
27,Citrus,Orange,2,Rutaceae,Sapindales,"{'carbohydrates': 8.3, 'protein': 1, 'fat': 0...."
28,Carica,Papaya,42,Caricaceae,Caricacea,"{'carbohydrates': 11, 'protein': 0, 'fat': 0.4..."
29,Passiflora,Passionfruit,70,Passifloraceae,Malpighiales,"{'carbohydrates': 22.4, 'protein': 2.2, 'fat':..."
30,Prunus,Peach,86,Rosaceae,Rosales,"{'carbohydrates': 9.5, 'protein': 0.9, 'fat': ..."
31,Pyrus,Pear,4,Rosaceae,Rosales,"{'carbohydrates': 15, 'protein': 0.4, 'fat': 0..."
32,Diospyros,Persimmon,52,Ebenaceae,Rosales,"{'carbohydrates': 18, 'protein': 0, 'fat': 0, ..."
33,Ananas,Pineapple,10,Bromeliaceae,Poales,"{'carbohydrates': 13.12, 'protein': 0.54, 'fat..."
34,Cactaceae,Pitahaya,78,Cactaceae,Caryophyllales,"{'carbohydrates': 7, 'protein': 1, 'fat': 0.4,..."
35,Prunus,Plum,71,Rosaceae,Rosales,"{'carbohydrates': 11.4, 'protein': 0.7, 'fat':..."
36,Punica,Pomegranate,79,Lythraceae,Myrtales,"{'carbohydrates': 18.7, 'protein': 1.7, 'fat':..."
37,Rubus,Raspberry,23,Rosaceae,Rosales,"{'carbohydrates': 12, 'protein': 1.2, 'fat': 0..."
38,Fragaria,Strawberry,3,Rosaceae,Rosales,"{'carbohydrates': 5.5, 'protein': 0.8, 'fat': ..."
39,Citrus,Tangerine,77,Rutaceae,Sapindales,"{'carbohydrates': 8.3, 'protein': 0, 'fat': 0...."
40,Solanum,Tomato,5,Solanaceae,Solanales,"{'carbohydrates': 3.9, 'protein': 0.9, 'fat': ..."
41,Citrullus,Watermelon,25,Cucurbitaceae,Cucurbitales,"{'carbohydrates': 8, 'protein': 0.6, 'fat': 0...."

The result is in a nested json format. The 'nutrition' column contains multiple subcolumns, so the data needs to be 'flattened' or normalized.

In [20]:
df2 = pd.json_normalize(result)

In [21]:
df2

,genus,name,id,family,order,nutritions.carbohydrates,nutritions.protein,nutritions.fat,nutritions.calories,nutritions.sugar
0,Malus,Apple,6,Rosaceae,Rosales,11.40,0.30,0.40,52,10.30
1,Prunus,Apricot,35,Rosaceae,Rosales,3.90,0.50,0.10,15,3.20
2,Persea,Avocado,84,Lauraceae,Laurales,8.53,2.00,14.66,160,0.66
3,Musa,Banana,1,Musaceae,Zingiberales,22.00,1.00,0.20,96,17.20
4,Rubus,Blackberry,64,Rosaceae,Rosales,9.00,1.30,0.40,40,4.50
5,Fragaria,Blueberry,33,Rosaceae,Rosales,5.50,0.00,0.40,29,5.40
6,Prunus,Cherry,9,Rosaceae,Rosales,12.00,1.00,0.30,50,8.00
7,Theobroma,Chocolate,88,Malvaceae,Malvales,58.00,8.51,30.57,531,54.00
8,Vaccinium,Cranberry,87,Ericaceae,Ericales,12.20,0.40,0.10,46,4.00
9,Selenicereus,Dragonfruit,80,Cactaceae,Caryophyllales,9.00,9.00,1.50,60,8.00
10,Durio,Durian,60,Malvaceae,Malvales,27.10,1.50,5.30,147,6.75
11,Sellowiana,Feijoa,76,Myrtaceae,Myrtoideae,8.00,0.60,0.40,44,3.00
12,Ficus,Fig,68,Moraceae,Rosales,19.00,0.80,0.30,74,16.00
13,Ribes,Gooseberry,69,Grossulariaceae,Saxifragales,10.00,0.90,0.60,44,0.00
14,Vitis,Grape,81,Vitaceae,Vitales,18.10,0.72,0.16,69,16.00
15,Vitis,Grapes,47,Vitaceae,Vitales,18.10,0.72,0.16,69,15.48
16,Malus,GreenApple,72,Rosaceae,Rosales,3.10,0.40,0.10,21,6.40
17,Psidium,Guava,37,Myrtaceae,Myrtales,14.00,2.60,1.00,68,9.00
18,Apteryx,Kiwi,66,Actinidiaceae,Struthioniformes,15.00,1.10,0.50,61,9.00
19,Actinidia,Kiwifruit,85,Actinidiaceae,Ericales,14.60,1.14,0.50,61,8.90
20,Citrus,Lemon,26,Rutaceae,Sapindales,9.00,1.10,0.30,29,2.50
21,Citrus,Lime,44,Rutaceae,Sapindales,8.40,0.30,0.10,25,1.70
22,Vaccinium,Lingonberry,65,Ericaceae,Ericales,11.30,0.75,0.34,50,5.74
23,Litchi,Lychee,67,Sapindaceae,Sapindales,17.00,0.80,0.44,66,15.00
24,Mangifera,Mango,27,Anacardiaceae,Sapindales,15.00,0.82,0.38,60,13.70
25,Cucumis,Melon,41,Cucurbitaceae,Cucurbitaceae,8.00,0.00,0.00,34,8.00
26,Morus,Morus,82,Moraceae,Rosales,9.80,1.44,0.39,43,8.10
27,Citrus,Orange,2,Rutaceae,Sapindales,8.30,1.00,0.20,43,8.20
28,Carica,Papaya,42,Caricaceae,Caricacea,11.00,0.00,0.40,43,1.00
29,Passiflora,Passionfruit,70,Passifloraceae,Malpighiales,22.40,2.20,0.70,97,11.20
30,Prunus,Peach,86,Rosaceae,Rosales,9.50,0.90,0.25,39,8.40
31,Pyrus,Pear,4,Rosaceae,Rosales,15.00,0.40,0.10,57,10.00
32,Diospyros,Persimmon,52,Ebenaceae,Rosales,18.00,0.00,0.00,81,18.00
33,Ananas,Pineapple,10,Bromeliaceae,Poales,13.12,0.54,0.12,50,9.85
34,Cactaceae,Pitahaya,78,Cactaceae,Caryophyllales,7.00,1.00,0.40,36,3.00
35,Prunus,Plum,71,Rosaceae,Rosales,11.40,0.70,0.28,46,9.92
36,Punica,Pomegranate,79,Lythraceae,Myrtales,18.70,1.70,1.20,83,13.70
37,Rubus,Raspberry,23,Rosaceae,Rosales,12.00,1.20,0.70,53,4.40
38,Fragaria,Strawberry,3,Rosaceae,Rosales,5.50,0.80,0.40,29,5.40
39,Citrus,Tangerine,77,Rutaceae,Sapindales,8.30,0.00,0.40,45,9.10
40,Solanum,Tomato,5,Solanaceae,Solanales,3.90,0.90,0.20,74,2.60
41,Citrullus,Watermelon,25,Cucurbitaceae,Cucurbitales,8.00,0.60,0.20,30,6.00

Let's see if we can extract some information from this dataframe. Perhaps, we need to know the family and genus of a cherry.

In [22]:
Cherry = df2.loc[df2["name"] == "Cherry"]
(Cherry.iloc[0]["family"]) , (Cherry.iloc[0]['genus'])

('Rosaceae', 'Prunus')

## Exercise 2
In this Exercise, find out how many calories are contained in a banana.

In [23]:
banana = df2.loc[df2['name'] == 'Banana']
banana.iloc[0]['nutritions.calories']

96

## Exercise 3

This [page](https://github.com/public-apis/public-apis#animals) contains a list of free public APIs. Choose any API of your interest and use it to load/extract some information, as shown in the example above.
1. Using `requests.get("url")` function, load your data.

In [24]:
d2 = r.get('https://github.com/public-apis/public-apis#animals')

In [27]:
reslt = json.loads(d2.text)

JSONDecodeError: ignored